
public class Exception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try
		{
			int a=20/0;
			System.out.println(a);
		}
		
		catch(ArithmeticException e)
		{
			e.printStackTrace();
			System.out.println("caught");
			
		}
		
		finally
		{
			System.out.println("fianlly");
		}

	}

}

output:-

caught
fianlly
